### ISSUE TITLE
Make a nice log-in page

### ISSUE THREAD

**Issue by mmmoli** [ContactTracing-app/Frontend#13]
It's super bare-bones right now.

It uses Gatsby _shadowing_ feature. We're overriding a component here:
https://github.com/ContactTracing-app/Frontend/blob/master/src/gatsby-theme-firebase/components/Form.tsx

**Comment by pongponk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make a nice log-in page](https://trello.com/c/gnNnPqVB/7-make-a-nice-log-in-page)

**Comment by magfurulabeer** [comment]
I'll work on this

**Comment by mmmoli** [comment]
To help @magfurulabeer, I messed-around with the login page for #37 . It's nicer now (ish)
