### ISSUE TITLE
Setting notification preference - Email/SMS

### ISSUE THREAD

**Issue by mmmoli** [ContactTracing-app/Frontend#15]
As a user, I need to be able to config how I want to be notified.

This information is stored in Firebase using Firestore, on registration, using [a Firebase Function](https://github.com/ContactTracing-app/Firebase-Functions/blob/master/functions/src/modules/users.ts#L28-L38)

# Tasks

- [x] Build UI to update the preferences
- [x] Commit preferences to Firebase

**Comment by pongponk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setting notification preference - Email/SMS](https://trello.com/c/3Z3t93rl/5-setting-notification-preference-email-sms)

**Comment by mmmoli** [comment]
Might be good to wait for #19 to set a way of doing things first.

**Comment by pongponk** [comment]
Here the wireframe: 
![image](https://user-images.githubusercontent.com/25208986/77699979-4111d580-6fab-11ea-9d5c-2782b022125d.png)

**Comment by firacloudtech** [comment]
I will tackle this part.

**Comment by mmmoli** [comment]
There is already an MR for this, but I'm happy for you to make your own branch and re-submit if it's easier.

(the old MR doesn't do much)

**Comment by mmmoli** [comment]
Closed with #41

**Comment by mmmoli** [comment]
@all-contributors please add @firacloudtech to code
