### ISSUE TITLE
Changing  Users' status

### ISSUE THREAD

**Issue by mmmoli** [ContactTracing-app/Frontend#16]
We need a way to collect these changes and commit them to the graph:
- Tested positive/negative
- In quarantine

Note: we're not storing this in Firebase; graph only please.

Relates to a task in #9.

**Comment by pongponk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Changing Users' status](https://trello.com/c/uIVCbWhB/4-changing-users-status)

**Comment by mmmoli** [comment]
Dup of #9
