### ISSUE TITLE
T&C

### ISSUE THREAD

**Issue by pongponk** [ContactTracing-app/Frontend#39]
Add T&C and Privacy Policy

https://getterms.io/g/2VbOrhD

**Comment by mmmoli** [comment]
We should turn these onto page on the site.

- [ ] Privacy Policy
- [ ] Add Terms of Service
- [ ] Add Cookie Policy
- [ ] Add small links in the footer.

**Comment by rebagliatte** [comment]
On it! Thanks for the additional details @mmmoli

**Comment by mmmoli** [comment]
@all-contributors please add @rebagliatte to code
