### ISSUE TITLE
Improve Share text

### ISSUE THREAD

**Issue by pongponk** [ContactTracing-app/Frontend#44]
Edit text when users share their profile link

**Comment by kevinamick** [comment]
This seems like a good place to start. I believe I need the real firebase creds to get started right?

**Comment by mmmoli** [comment]
Hey @kevinamick you're more than welcome!

I can hook you up with the FB creds. Wanna join the Slack so we can chat more?
https://join.slack.com/t/contacttracingapp/shared_invite/zt-dc6x0qxg-epi0LpT8zJM~VL3ss365Fg

**Comment by mmmoli** [comment]
@kevinamick Files you need are here: https://github.com/ContactTracing-app/Frontend/blob/master/src/app/ShareView/IconList.tsx

@pongponk is drafting the new string…

**Comment by pongponk** [comment]
> This is me on Contact Tracing App. Join me so we can keep each other safe {link}

**Comment by mmmoli** [comment]
Closed with #54
