### ISSUE TITLE
Create UI to show previous log entries

### ISSUE THREAD

**Issue by mmmoli** [ContactTracing-app/Frontend#6]
Given that we let people log contact, we should have a way to unlog that contact too.

This UI should let someone pick a date in the past and see `logEntries` for that day

#19 will help.

**Comment by pongponk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create UI to show previous log entries](https://trello.com/c/aGivWeDb/14-create-ui-to-show-previous-log-entries)

**Comment by mmmoli** [comment]
- [ ] @pongponk is coming-up with some kind of design

**Comment by pongponk** [comment]
Here's the design:
![image](https://user-images.githubusercontent.com/25208986/77702472-82f14a80-6fb0-11ea-9242-648690ad46fe.png)

Figma file: https://www.figma.com/file/CFy0c183XgjiPfUMRuuFYt/Contact-tracing?node-id=373%3A0
