### ISSUE TITLE
Fire the important Firebase analytics events

### ISSUE THREAD

**Issue by mmmoli** [ContactTracing-app/Frontend#8]

**Comment by pongponk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fire the important Firebase analytics events](https://trello.com/c/U9iV4UCX/12-fire-the-important-firebase-analytics-events)

**Comment by mmmoli** [comment]
Here's a list

- [ ] On log of contact
- [ ] On unlog of contact
- [ ] On invite made/connection made
